# Generated by Django 4.2.13 on 2024-08-08 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_alter_shippingaddress_shipping_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippin_address',
            new_name='shipping_address',
        ),
    ]
