# Generated by Django 4.2.13 on 2024-06-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_alter_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
